/*
 * Generated by MTK DrvGen Version 10.01.0 for MT6260NP. Copyright MediaTek Inc. (C) 2012.
 * Sun Oct 26 20:24:27 2025
 * Do Not Modify the File.
 */

#ifndef _PMIC_DRV_H
#define _PMIC_DRV_H


//init setting
//Application name


#endif /* _PMIC_DRV_H */


