/*
 * Generated by MTK DrvGen Version 10.01.0 for MT6260NP. Copyright MediaTek Inc. (C) 2012.
 * Sun Oct 26 20:24:27 2025
 * Do Not Modify the File.
 */

#ifdef __CUST_NEW__
#include "pmic_drv.h"
#include "dcl.h"


void pmu_drv_tool_customization_init(void)  
 {}  
 #endif /* __CUST_NEW__ */


